language: go
go:
  - 1.13.x
  - 1.14.x
  - 1.15.x
  - 1.16.x
  - master

go_import_path: github.com/go-gosh/tomato

before_install:
  - go get -t -v ./...

script:
  - make test

after_success:
  - bash <(curl -s https://codecov.io/bash)