//go:build ignore
// +build ignore

// embed config.example.yaml in binary file
package main

import (
	"bytes"
	"io/ioutil"
	"strconv"
)

func main() {
	fp, err := ioutil.ReadFile("./metadata/config.example.yaml")
	if err != nil {
		panic(err)
	}
	var s bytes.Buffer
	s.WriteString(`// Code generated by tomato, DO NOT EDIT.
//go:build !go1.16
// +build !go1.16

package config

//go:generate go run -mod=mod embed_under_1_16.go
var defaultConfigSource = []byte{`)
	for i, b := range fp {
		s.WriteString(strconv.Itoa(int(b)))
		if i < len(fp)-1 {
			s.WriteString(", ")
		}
	}
	s.WriteString("}\n")
	err = ioutil.WriteFile("./default.go", s.Bytes(), 0644)
	if err != nil {
		panic(err)
	}
}
