// Code generated by entc, DO NOT EDIT.

package ent

import (
	"context"
	"fmt"
	"sync"
	"time"

	"github.com/go-gosh/tomato/app/ent/predicate"
	"github.com/go-gosh/tomato/app/ent/user"
	"github.com/go-gosh/tomato/app/ent/userconfig"
	"github.com/go-gosh/tomato/app/ent/usertomato"

	"entgo.io/ent"
)

const (
	// Operation types.
	OpCreate    = ent.OpCreate
	OpDelete    = ent.OpDelete
	OpDeleteOne = ent.OpDeleteOne
	OpUpdate    = ent.OpUpdate
	OpUpdateOne = ent.OpUpdateOne

	// Node types.
	TypeUser       = "User"
	TypeUserConfig = "UserConfig"
	TypeUserTomato = "UserTomato"
)

// UserMutation represents an operation that mutates the User nodes in the graph.
type UserMutation struct {
	config
	op                   Op
	typ                  string
	id                   *int
	created_at           *time.Time
	updated_at           *time.Time
	username             *string
	password             *string
	enabled              *bool
	clearedFields        map[string]struct{}
	user_configs         map[int]struct{}
	removeduser_configs  map[int]struct{}
	cleareduser_configs  bool
	user_tomatoes        map[int]struct{}
	removeduser_tomatoes map[int]struct{}
	cleareduser_tomatoes bool
	done                 bool
	oldValue             func(context.Context) (*User, error)
	predicates           []predicate.User
}

var _ ent.Mutation = (*UserMutation)(nil)

// userOption allows management of the mutation configuration using functional options.
type userOption func(*UserMutation)

// newUserMutation creates new mutation for the User entity.
func newUserMutation(c config, op Op, opts ...userOption) *UserMutation {
	m := &UserMutation{
		config:        c,
		op:            op,
		typ:           TypeUser,
		clearedFields: make(map[string]struct{}),
	}
	for _, opt := range opts {
		opt(m)
	}
	return m
}

// withUserID sets the ID field of the mutation.
func withUserID(id int) userOption {
	return func(m *UserMutation) {
		var (
			err   error
			once  sync.Once
			value *User
		)
		m.oldValue = func(ctx context.Context) (*User, error) {
			once.Do(func() {
				if m.done {
					err = fmt.Errorf("querying old values post mutation is not allowed")
				} else {
					value, err = m.Client().User.Get(ctx, id)
				}
			})
			return value, err
		}
		m.id = &id
	}
}

// withUser sets the old User of the mutation.
func withUser(node *User) userOption {
	return func(m *UserMutation) {
		m.oldValue = func(context.Context) (*User, error) {
			return node, nil
		}
		m.id = &node.ID
	}
}

// Client returns a new `ent.Client` from the mutation. If the mutation was
// executed in a transaction (ent.Tx), a transactional client is returned.
func (m UserMutation) Client() *Client {
	client := &Client{config: m.config}
	client.init()
	return client
}

// Tx returns an `ent.Tx` for mutations that were executed in transactions;
// it returns an error otherwise.
func (m UserMutation) Tx() (*Tx, error) {
	if _, ok := m.driver.(*txDriver); !ok {
		return nil, fmt.Errorf("ent: mutation is not running in a transaction")
	}
	tx := &Tx{config: m.config}
	tx.init()
	return tx, nil
}

// ID returns the ID value in the mutation. Note that the ID is only available
// if it was provided to the builder or after it was returned from the database.
func (m *UserMutation) ID() (id int, exists bool) {
	if m.id == nil {
		return
	}
	return *m.id, true
}

// SetCreatedAt sets the "created_at" field.
func (m *UserMutation) SetCreatedAt(t time.Time) {
	m.created_at = &t
}

// CreatedAt returns the value of the "created_at" field in the mutation.
func (m *UserMutation) CreatedAt() (r time.Time, exists bool) {
	v := m.created_at
	if v == nil {
		return
	}
	return *v, true
}

// OldCreatedAt returns the old "created_at" field's value of the User entity.
// If the User object wasn't provided to the builder, the object is fetched from the database.
// An error is returned if the mutation operation is not UpdateOne, or the database query fails.
func (m *UserMutation) OldCreatedAt(ctx context.Context) (v time.Time, err error) {
	if !m.op.Is(OpUpdateOne) {
		return v, fmt.Errorf("OldCreatedAt is only allowed on UpdateOne operations")
	}
	if m.id == nil || m.oldValue == nil {
		return v, fmt.Errorf("OldCreatedAt requires an ID field in the mutation")
	}
	oldValue, err := m.oldValue(ctx)
	if err != nil {
		return v, fmt.Errorf("querying old value for OldCreatedAt: %w", err)
	}
	return oldValue.CreatedAt, nil
}

// ResetCreatedAt resets all changes to the "created_at" field.
func (m *UserMutation) ResetCreatedAt() {
	m.created_at = nil
}

// SetUpdatedAt sets the "updated_at" field.
func (m *UserMutation) SetUpdatedAt(t time.Time) {
	m.updated_at = &t
}

// UpdatedAt returns the value of the "updated_at" field in the mutation.
func (m *UserMutation) UpdatedAt() (r time.Time, exists bool) {
	v := m.updated_at
	if v == nil {
		return
	}
	return *v, true
}

// OldUpdatedAt returns the old "updated_at" field's value of the User entity.
// If the User object wasn't provided to the builder, the object is fetched from the database.
// An error is returned if the mutation operation is not UpdateOne, or the database query fails.
func (m *UserMutation) OldUpdatedAt(ctx context.Context) (v time.Time, err error) {
	if !m.op.Is(OpUpdateOne) {
		return v, fmt.Errorf("OldUpdatedAt is only allowed on UpdateOne operations")
	}
	if m.id == nil || m.oldValue == nil {
		return v, fmt.Errorf("OldUpdatedAt requires an ID field in the mutation")
	}
	oldValue, err := m.oldValue(ctx)
	if err != nil {
		return v, fmt.Errorf("querying old value for OldUpdatedAt: %w", err)
	}
	return oldValue.UpdatedAt, nil
}

// ResetUpdatedAt resets all changes to the "updated_at" field.
func (m *UserMutation) ResetUpdatedAt() {
	m.updated_at = nil
}

// SetUsername sets the "username" field.
func (m *UserMutation) SetUsername(s string) {
	m.username = &s
}

// Username returns the value of the "username" field in the mutation.
func (m *UserMutation) Username() (r string, exists bool) {
	v := m.username
	if v == nil {
		return
	}
	return *v, true
}

// OldUsername returns the old "username" field's value of the User entity.
// If the User object wasn't provided to the builder, the object is fetched from the database.
// An error is returned if the mutation operation is not UpdateOne, or the database query fails.
func (m *UserMutation) OldUsername(ctx context.Context) (v string, err error) {
	if !m.op.Is(OpUpdateOne) {
		return v, fmt.Errorf("OldUsername is only allowed on UpdateOne operations")
	}
	if m.id == nil || m.oldValue == nil {
		return v, fmt.Errorf("OldUsername requires an ID field in the mutation")
	}
	oldValue, err := m.oldValue(ctx)
	if err != nil {
		return v, fmt.Errorf("querying old value for OldUsername: %w", err)
	}
	return oldValue.Username, nil
}

// ResetUsername resets all changes to the "username" field.
func (m *UserMutation) ResetUsername() {
	m.username = nil
}

// SetPassword sets the "password" field.
func (m *UserMutation) SetPassword(s string) {
	m.password = &s
}

// Password returns the value of the "password" field in the mutation.
func (m *UserMutation) Password() (r string, exists bool) {
	v := m.password
	if v == nil {
		return
	}
	return *v, true
}

// OldPassword returns the old "password" field's value of the User entity.
// If the User object wasn't provided to the builder, the object is fetched from the database.
// An error is returned if the mutation operation is not UpdateOne, or the database query fails.
func (m *UserMutation) OldPassword(ctx context.Context) (v string, err error) {
	if !m.op.Is(OpUpdateOne) {
		return v, fmt.Errorf("OldPassword is only allowed on UpdateOne operations")
	}
	if m.id == nil || m.oldValue == nil {
		return v, fmt.Errorf("OldPassword requires an ID field in the mutation")
	}
	oldValue, err := m.oldValue(ctx)
	if err != nil {
		return v, fmt.Errorf("querying old value for OldPassword: %w", err)
	}
	return oldValue.Password, nil
}

// ResetPassword resets all changes to the "password" field.
func (m *UserMutation) ResetPassword() {
	m.password = nil
}

// SetEnabled sets the "enabled" field.
func (m *UserMutation) SetEnabled(b bool) {
	m.enabled = &b
}

// Enabled returns the value of the "enabled" field in the mutation.
func (m *UserMutation) Enabled() (r bool, exists bool) {
	v := m.enabled
	if v == nil {
		return
	}
	return *v, true
}

// OldEnabled returns the old "enabled" field's value of the User entity.
// If the User object wasn't provided to the builder, the object is fetched from the database.
// An error is returned if the mutation operation is not UpdateOne, or the database query fails.
func (m *UserMutation) OldEnabled(ctx context.Context) (v bool, err error) {
	if !m.op.Is(OpUpdateOne) {
		return v, fmt.Errorf("OldEnabled is only allowed on UpdateOne operations")
	}
	if m.id == nil || m.oldValue == nil {
		return v, fmt.Errorf("OldEnabled requires an ID field in the mutation")
	}
	oldValue, err := m.oldValue(ctx)
	if err != nil {
		return v, fmt.Errorf("querying old value for OldEnabled: %w", err)
	}
	return oldValue.Enabled, nil
}

// ResetEnabled resets all changes to the "enabled" field.
func (m *UserMutation) ResetEnabled() {
	m.enabled = nil
}

// AddUserConfigIDs adds the "user_configs" edge to the UserConfig entity by ids.
func (m *UserMutation) AddUserConfigIDs(ids ...int) {
	if m.user_configs == nil {
		m.user_configs = make(map[int]struct{})
	}
	for i := range ids {
		m.user_configs[ids[i]] = struct{}{}
	}
}

// ClearUserConfigs clears the "user_configs" edge to the UserConfig entity.
func (m *UserMutation) ClearUserConfigs() {
	m.cleareduser_configs = true
}

// UserConfigsCleared reports if the "user_configs" edge to the UserConfig entity was cleared.
func (m *UserMutation) UserConfigsCleared() bool {
	return m.cleareduser_configs
}

// RemoveUserConfigIDs removes the "user_configs" edge to the UserConfig entity by IDs.
func (m *UserMutation) RemoveUserConfigIDs(ids ...int) {
	if m.removeduser_configs == nil {
		m.removeduser_configs = make(map[int]struct{})
	}
	for i := range ids {
		delete(m.user_configs, ids[i])
		m.removeduser_configs[ids[i]] = struct{}{}
	}
}

// RemovedUserConfigs returns the removed IDs of the "user_configs" edge to the UserConfig entity.
func (m *UserMutation) RemovedUserConfigsIDs() (ids []int) {
	for id := range m.removeduser_configs {
		ids = append(ids, id)
	}
	return
}

// UserConfigsIDs returns the "user_configs" edge IDs in the mutation.
func (m *UserMutation) UserConfigsIDs() (ids []int) {
	for id := range m.user_configs {
		ids = append(ids, id)
	}
	return
}

// ResetUserConfigs resets all changes to the "user_configs" edge.
func (m *UserMutation) ResetUserConfigs() {
	m.user_configs = nil
	m.cleareduser_configs = false
	m.removeduser_configs = nil
}

// AddUserTomatoIDs adds the "user_tomatoes" edge to the UserTomato entity by ids.
func (m *UserMutation) AddUserTomatoIDs(ids ...int) {
	if m.user_tomatoes == nil {
		m.user_tomatoes = make(map[int]struct{})
	}
	for i := range ids {
		m.user_tomatoes[ids[i]] = struct{}{}
	}
}

// ClearUserTomatoes clears the "user_tomatoes" edge to the UserTomato entity.
func (m *UserMutation) ClearUserTomatoes() {
	m.cleareduser_tomatoes = true
}

// UserTomatoesCleared reports if the "user_tomatoes" edge to the UserTomato entity was cleared.
func (m *UserMutation) UserTomatoesCleared() bool {
	return m.cleareduser_tomatoes
}

// RemoveUserTomatoIDs removes the "user_tomatoes" edge to the UserTomato entity by IDs.
func (m *UserMutation) RemoveUserTomatoIDs(ids ...int) {
	if m.removeduser_tomatoes == nil {
		m.removeduser_tomatoes = make(map[int]struct{})
	}
	for i := range ids {
		delete(m.user_tomatoes, ids[i])
		m.removeduser_tomatoes[ids[i]] = struct{}{}
	}
}

// RemovedUserTomatoes returns the removed IDs of the "user_tomatoes" edge to the UserTomato entity.
func (m *UserMutation) RemovedUserTomatoesIDs() (ids []int) {
	for id := range m.removeduser_tomatoes {
		ids = append(ids, id)
	}
	return
}

// UserTomatoesIDs returns the "user_tomatoes" edge IDs in the mutation.
func (m *UserMutation) UserTomatoesIDs() (ids []int) {
	for id := range m.user_tomatoes {
		ids = append(ids, id)
	}
	return
}

// ResetUserTomatoes resets all changes to the "user_tomatoes" edge.
func (m *UserMutation) ResetUserTomatoes() {
	m.user_tomatoes = nil
	m.cleareduser_tomatoes = false
	m.removeduser_tomatoes = nil
}

// Where appends a list predicates to the UserMutation builder.
func (m *UserMutation) Where(ps ...predicate.User) {
	m.predicates = append(m.predicates, ps...)
}

// Op returns the operation name.
func (m *UserMutation) Op() Op {
	return m.op
}

// Type returns the node type of this mutation (User).
func (m *UserMutation) Type() string {
	return m.typ
}

// Fields returns all fields that were changed during this mutation. Note that in
// order to get all numeric fields that were incremented/decremented, call
// AddedFields().
func (m *UserMutation) Fields() []string {
	fields := make([]string, 0, 5)
	if m.created_at != nil {
		fields = append(fields, user.FieldCreatedAt)
	}
	if m.updated_at != nil {
		fields = append(fields, user.FieldUpdatedAt)
	}
	if m.username != nil {
		fields = append(fields, user.FieldUsername)
	}
	if m.password != nil {
		fields = append(fields, user.FieldPassword)
	}
	if m.enabled != nil {
		fields = append(fields, user.FieldEnabled)
	}
	return fields
}

// Field returns the value of a field with the given name. The second boolean
// return value indicates that this field was not set, or was not defined in the
// schema.
func (m *UserMutation) Field(name string) (ent.Value, bool) {
	switch name {
	case user.FieldCreatedAt:
		return m.CreatedAt()
	case user.FieldUpdatedAt:
		return m.UpdatedAt()
	case user.FieldUsername:
		return m.Username()
	case user.FieldPassword:
		return m.Password()
	case user.FieldEnabled:
		return m.Enabled()
	}
	return nil, false
}

// OldField returns the old value of the field from the database. An error is
// returned if the mutation operation is not UpdateOne, or the query to the
// database failed.
func (m *UserMutation) OldField(ctx context.Context, name string) (ent.Value, error) {
	switch name {
	case user.FieldCreatedAt:
		return m.OldCreatedAt(ctx)
	case user.FieldUpdatedAt:
		return m.OldUpdatedAt(ctx)
	case user.FieldUsername:
		return m.OldUsername(ctx)
	case user.FieldPassword:
		return m.OldPassword(ctx)
	case user.FieldEnabled:
		return m.OldEnabled(ctx)
	}
	return nil, fmt.Errorf("unknown User field %s", name)
}

// SetField sets the value of a field with the given name. It returns an error if
// the field is not defined in the schema, or if the type mismatched the field
// type.
func (m *UserMutation) SetField(name string, value ent.Value) error {
	switch name {
	case user.FieldCreatedAt:
		v, ok := value.(time.Time)
		if !ok {
			return fmt.Errorf("unexpected type %T for field %s", value, name)
		}
		m.SetCreatedAt(v)
		return nil
	case user.FieldUpdatedAt:
		v, ok := value.(time.Time)
		if !ok {
			return fmt.Errorf("unexpected type %T for field %s", value, name)
		}
		m.SetUpdatedAt(v)
		return nil
	case user.FieldUsername:
		v, ok := value.(string)
		if !ok {
			return fmt.Errorf("unexpected type %T for field %s", value, name)
		}
		m.SetUsername(v)
		return nil
	case user.FieldPassword:
		v, ok := value.(string)
		if !ok {
			return fmt.Errorf("unexpected type %T for field %s", value, name)
		}
		m.SetPassword(v)
		return nil
	case user.FieldEnabled:
		v, ok := value.(bool)
		if !ok {
			return fmt.Errorf("unexpected type %T for field %s", value, name)
		}
		m.SetEnabled(v)
		return nil
	}
	return fmt.Errorf("unknown User field %s", name)
}

// AddedFields returns all numeric fields that were incremented/decremented during
// this mutation.
func (m *UserMutation) AddedFields() []string {
	return nil
}

// AddedField returns the numeric value that was incremented/decremented on a field
// with the given name. The second boolean return value indicates that this field
// was not set, or was not defined in the schema.
func (m *UserMutation) AddedField(name string) (ent.Value, bool) {
	return nil, false
}

// AddField adds the value to the field with the given name. It returns an error if
// the field is not defined in the schema, or if the type mismatched the field
// type.
func (m *UserMutation) AddField(name string, value ent.Value) error {
	switch name {
	}
	return fmt.Errorf("unknown User numeric field %s", name)
}

// ClearedFields returns all nullable fields that were cleared during this
// mutation.
func (m *UserMutation) ClearedFields() []string {
	return nil
}

// FieldCleared returns a boolean indicating if a field with the given name was
// cleared in this mutation.
func (m *UserMutation) FieldCleared(name string) bool {
	_, ok := m.clearedFields[name]
	return ok
}

// ClearField clears the value of the field with the given name. It returns an
// error if the field is not defined in the schema.
func (m *UserMutation) ClearField(name string) error {
	return fmt.Errorf("unknown User nullable field %s", name)
}

// ResetField resets all changes in the mutation for the field with the given name.
// It returns an error if the field is not defined in the schema.
func (m *UserMutation) ResetField(name string) error {
	switch name {
	case user.FieldCreatedAt:
		m.ResetCreatedAt()
		return nil
	case user.FieldUpdatedAt:
		m.ResetUpdatedAt()
		return nil
	case user.FieldUsername:
		m.ResetUsername()
		return nil
	case user.FieldPassword:
		m.ResetPassword()
		return nil
	case user.FieldEnabled:
		m.ResetEnabled()
		return nil
	}
	return fmt.Errorf("unknown User field %s", name)
}

// AddedEdges returns all edge names that were set/added in this mutation.
func (m *UserMutation) AddedEdges() []string {
	edges := make([]string, 0, 2)
	if m.user_configs != nil {
		edges = append(edges, user.EdgeUserConfigs)
	}
	if m.user_tomatoes != nil {
		edges = append(edges, user.EdgeUserTomatoes)
	}
	return edges
}

// AddedIDs returns all IDs (to other nodes) that were added for the given edge
// name in this mutation.
func (m *UserMutation) AddedIDs(name string) []ent.Value {
	switch name {
	case user.EdgeUserConfigs:
		ids := make([]ent.Value, 0, len(m.user_configs))
		for id := range m.user_configs {
			ids = append(ids, id)
		}
		return ids
	case user.EdgeUserTomatoes:
		ids := make([]ent.Value, 0, len(m.user_tomatoes))
		for id := range m.user_tomatoes {
			ids = append(ids, id)
		}
		return ids
	}
	return nil
}

// RemovedEdges returns all edge names that were removed in this mutation.
func (m *UserMutation) RemovedEdges() []string {
	edges := make([]string, 0, 2)
	if m.removeduser_configs != nil {
		edges = append(edges, user.EdgeUserConfigs)
	}
	if m.removeduser_tomatoes != nil {
		edges = append(edges, user.EdgeUserTomatoes)
	}
	return edges
}

// RemovedIDs returns all IDs (to other nodes) that were removed for the edge with
// the given name in this mutation.
func (m *UserMutation) RemovedIDs(name string) []ent.Value {
	switch name {
	case user.EdgeUserConfigs:
		ids := make([]ent.Value, 0, len(m.removeduser_configs))
		for id := range m.removeduser_configs {
			ids = append(ids, id)
		}
		return ids
	case user.EdgeUserTomatoes:
		ids := make([]ent.Value, 0, len(m.removeduser_tomatoes))
		for id := range m.removeduser_tomatoes {
			ids = append(ids, id)
		}
		return ids
	}
	return nil
}

// ClearedEdges returns all edge names that were cleared in this mutation.
func (m *UserMutation) ClearedEdges() []string {
	edges := make([]string, 0, 2)
	if m.cleareduser_configs {
		edges = append(edges, user.EdgeUserConfigs)
	}
	if m.cleareduser_tomatoes {
		edges = append(edges, user.EdgeUserTomatoes)
	}
	return edges
}

// EdgeCleared returns a boolean which indicates if the edge with the given name
// was cleared in this mutation.
func (m *UserMutation) EdgeCleared(name string) bool {
	switch name {
	case user.EdgeUserConfigs:
		return m.cleareduser_configs
	case user.EdgeUserTomatoes:
		return m.cleareduser_tomatoes
	}
	return false
}

// ClearEdge clears the value of the edge with the given name. It returns an error
// if that edge is not defined in the schema.
func (m *UserMutation) ClearEdge(name string) error {
	switch name {
	}
	return fmt.Errorf("unknown User unique edge %s", name)
}

// ResetEdge resets all changes to the edge with the given name in this mutation.
// It returns an error if the edge is not defined in the schema.
func (m *UserMutation) ResetEdge(name string) error {
	switch name {
	case user.EdgeUserConfigs:
		m.ResetUserConfigs()
		return nil
	case user.EdgeUserTomatoes:
		m.ResetUserTomatoes()
		return nil
	}
	return fmt.Errorf("unknown User edge %s", name)
}

// UserConfigMutation represents an operation that mutates the UserConfig nodes in the graph.
type UserConfigMutation struct {
	config
	op            Op
	typ           string
	id            *int
	rank          *uint8
	addrank       *uint8
	working       *uint8
	addworking    *uint8
	_break        *uint8
	add_break     *uint8
	clearedFields map[string]struct{}
	users         *int
	clearedusers  bool
	done          bool
	oldValue      func(context.Context) (*UserConfig, error)
	predicates    []predicate.UserConfig
}

var _ ent.Mutation = (*UserConfigMutation)(nil)

// userconfigOption allows management of the mutation configuration using functional options.
type userconfigOption func(*UserConfigMutation)

// newUserConfigMutation creates new mutation for the UserConfig entity.
func newUserConfigMutation(c config, op Op, opts ...userconfigOption) *UserConfigMutation {
	m := &UserConfigMutation{
		config:        c,
		op:            op,
		typ:           TypeUserConfig,
		clearedFields: make(map[string]struct{}),
	}
	for _, opt := range opts {
		opt(m)
	}
	return m
}

// withUserConfigID sets the ID field of the mutation.
func withUserConfigID(id int) userconfigOption {
	return func(m *UserConfigMutation) {
		var (
			err   error
			once  sync.Once
			value *UserConfig
		)
		m.oldValue = func(ctx context.Context) (*UserConfig, error) {
			once.Do(func() {
				if m.done {
					err = fmt.Errorf("querying old values post mutation is not allowed")
				} else {
					value, err = m.Client().UserConfig.Get(ctx, id)
				}
			})
			return value, err
		}
		m.id = &id
	}
}

// withUserConfig sets the old UserConfig of the mutation.
func withUserConfig(node *UserConfig) userconfigOption {
	return func(m *UserConfigMutation) {
		m.oldValue = func(context.Context) (*UserConfig, error) {
			return node, nil
		}
		m.id = &node.ID
	}
}

// Client returns a new `ent.Client` from the mutation. If the mutation was
// executed in a transaction (ent.Tx), a transactional client is returned.
func (m UserConfigMutation) Client() *Client {
	client := &Client{config: m.config}
	client.init()
	return client
}

// Tx returns an `ent.Tx` for mutations that were executed in transactions;
// it returns an error otherwise.
func (m UserConfigMutation) Tx() (*Tx, error) {
	if _, ok := m.driver.(*txDriver); !ok {
		return nil, fmt.Errorf("ent: mutation is not running in a transaction")
	}
	tx := &Tx{config: m.config}
	tx.init()
	return tx, nil
}

// ID returns the ID value in the mutation. Note that the ID is only available
// if it was provided to the builder or after it was returned from the database.
func (m *UserConfigMutation) ID() (id int, exists bool) {
	if m.id == nil {
		return
	}
	return *m.id, true
}

// SetRank sets the "rank" field.
func (m *UserConfigMutation) SetRank(u uint8) {
	m.rank = &u
	m.addrank = nil
}

// Rank returns the value of the "rank" field in the mutation.
func (m *UserConfigMutation) Rank() (r uint8, exists bool) {
	v := m.rank
	if v == nil {
		return
	}
	return *v, true
}

// OldRank returns the old "rank" field's value of the UserConfig entity.
// If the UserConfig object wasn't provided to the builder, the object is fetched from the database.
// An error is returned if the mutation operation is not UpdateOne, or the database query fails.
func (m *UserConfigMutation) OldRank(ctx context.Context) (v uint8, err error) {
	if !m.op.Is(OpUpdateOne) {
		return v, fmt.Errorf("OldRank is only allowed on UpdateOne operations")
	}
	if m.id == nil || m.oldValue == nil {
		return v, fmt.Errorf("OldRank requires an ID field in the mutation")
	}
	oldValue, err := m.oldValue(ctx)
	if err != nil {
		return v, fmt.Errorf("querying old value for OldRank: %w", err)
	}
	return oldValue.Rank, nil
}

// AddRank adds u to the "rank" field.
func (m *UserConfigMutation) AddRank(u uint8) {
	if m.addrank != nil {
		*m.addrank += u
	} else {
		m.addrank = &u
	}
}

// AddedRank returns the value that was added to the "rank" field in this mutation.
func (m *UserConfigMutation) AddedRank() (r uint8, exists bool) {
	v := m.addrank
	if v == nil {
		return
	}
	return *v, true
}

// ResetRank resets all changes to the "rank" field.
func (m *UserConfigMutation) ResetRank() {
	m.rank = nil
	m.addrank = nil
}

// SetWorking sets the "working" field.
func (m *UserConfigMutation) SetWorking(u uint8) {
	m.working = &u
	m.addworking = nil
}

// Working returns the value of the "working" field in the mutation.
func (m *UserConfigMutation) Working() (r uint8, exists bool) {
	v := m.working
	if v == nil {
		return
	}
	return *v, true
}

// OldWorking returns the old "working" field's value of the UserConfig entity.
// If the UserConfig object wasn't provided to the builder, the object is fetched from the database.
// An error is returned if the mutation operation is not UpdateOne, or the database query fails.
func (m *UserConfigMutation) OldWorking(ctx context.Context) (v uint8, err error) {
	if !m.op.Is(OpUpdateOne) {
		return v, fmt.Errorf("OldWorking is only allowed on UpdateOne operations")
	}
	if m.id == nil || m.oldValue == nil {
		return v, fmt.Errorf("OldWorking requires an ID field in the mutation")
	}
	oldValue, err := m.oldValue(ctx)
	if err != nil {
		return v, fmt.Errorf("querying old value for OldWorking: %w", err)
	}
	return oldValue.Working, nil
}

// AddWorking adds u to the "working" field.
func (m *UserConfigMutation) AddWorking(u uint8) {
	if m.addworking != nil {
		*m.addworking += u
	} else {
		m.addworking = &u
	}
}

// AddedWorking returns the value that was added to the "working" field in this mutation.
func (m *UserConfigMutation) AddedWorking() (r uint8, exists bool) {
	v := m.addworking
	if v == nil {
		return
	}
	return *v, true
}

// ResetWorking resets all changes to the "working" field.
func (m *UserConfigMutation) ResetWorking() {
	m.working = nil
	m.addworking = nil
}

// SetBreak sets the "break" field.
func (m *UserConfigMutation) SetBreak(u uint8) {
	m._break = &u
	m.add_break = nil
}

// Break returns the value of the "break" field in the mutation.
func (m *UserConfigMutation) Break() (r uint8, exists bool) {
	v := m._break
	if v == nil {
		return
	}
	return *v, true
}

// OldBreak returns the old "break" field's value of the UserConfig entity.
// If the UserConfig object wasn't provided to the builder, the object is fetched from the database.
// An error is returned if the mutation operation is not UpdateOne, or the database query fails.
func (m *UserConfigMutation) OldBreak(ctx context.Context) (v uint8, err error) {
	if !m.op.Is(OpUpdateOne) {
		return v, fmt.Errorf("OldBreak is only allowed on UpdateOne operations")
	}
	if m.id == nil || m.oldValue == nil {
		return v, fmt.Errorf("OldBreak requires an ID field in the mutation")
	}
	oldValue, err := m.oldValue(ctx)
	if err != nil {
		return v, fmt.Errorf("querying old value for OldBreak: %w", err)
	}
	return oldValue.Break, nil
}

// AddBreak adds u to the "break" field.
func (m *UserConfigMutation) AddBreak(u uint8) {
	if m.add_break != nil {
		*m.add_break += u
	} else {
		m.add_break = &u
	}
}

// AddedBreak returns the value that was added to the "break" field in this mutation.
func (m *UserConfigMutation) AddedBreak() (r uint8, exists bool) {
	v := m.add_break
	if v == nil {
		return
	}
	return *v, true
}

// ResetBreak resets all changes to the "break" field.
func (m *UserConfigMutation) ResetBreak() {
	m._break = nil
	m.add_break = nil
}

// SetUsersID sets the "users" edge to the User entity by id.
func (m *UserConfigMutation) SetUsersID(id int) {
	m.users = &id
}

// ClearUsers clears the "users" edge to the User entity.
func (m *UserConfigMutation) ClearUsers() {
	m.clearedusers = true
}

// UsersCleared reports if the "users" edge to the User entity was cleared.
func (m *UserConfigMutation) UsersCleared() bool {
	return m.clearedusers
}

// UsersID returns the "users" edge ID in the mutation.
func (m *UserConfigMutation) UsersID() (id int, exists bool) {
	if m.users != nil {
		return *m.users, true
	}
	return
}

// UsersIDs returns the "users" edge IDs in the mutation.
// Note that IDs always returns len(IDs) <= 1 for unique edges, and you should use
// UsersID instead. It exists only for internal usage by the builders.
func (m *UserConfigMutation) UsersIDs() (ids []int) {
	if id := m.users; id != nil {
		ids = append(ids, *id)
	}
	return
}

// ResetUsers resets all changes to the "users" edge.
func (m *UserConfigMutation) ResetUsers() {
	m.users = nil
	m.clearedusers = false
}

// Where appends a list predicates to the UserConfigMutation builder.
func (m *UserConfigMutation) Where(ps ...predicate.UserConfig) {
	m.predicates = append(m.predicates, ps...)
}

// Op returns the operation name.
func (m *UserConfigMutation) Op() Op {
	return m.op
}

// Type returns the node type of this mutation (UserConfig).
func (m *UserConfigMutation) Type() string {
	return m.typ
}

// Fields returns all fields that were changed during this mutation. Note that in
// order to get all numeric fields that were incremented/decremented, call
// AddedFields().
func (m *UserConfigMutation) Fields() []string {
	fields := make([]string, 0, 3)
	if m.rank != nil {
		fields = append(fields, userconfig.FieldRank)
	}
	if m.working != nil {
		fields = append(fields, userconfig.FieldWorking)
	}
	if m._break != nil {
		fields = append(fields, userconfig.FieldBreak)
	}
	return fields
}

// Field returns the value of a field with the given name. The second boolean
// return value indicates that this field was not set, or was not defined in the
// schema.
func (m *UserConfigMutation) Field(name string) (ent.Value, bool) {
	switch name {
	case userconfig.FieldRank:
		return m.Rank()
	case userconfig.FieldWorking:
		return m.Working()
	case userconfig.FieldBreak:
		return m.Break()
	}
	return nil, false
}

// OldField returns the old value of the field from the database. An error is
// returned if the mutation operation is not UpdateOne, or the query to the
// database failed.
func (m *UserConfigMutation) OldField(ctx context.Context, name string) (ent.Value, error) {
	switch name {
	case userconfig.FieldRank:
		return m.OldRank(ctx)
	case userconfig.FieldWorking:
		return m.OldWorking(ctx)
	case userconfig.FieldBreak:
		return m.OldBreak(ctx)
	}
	return nil, fmt.Errorf("unknown UserConfig field %s", name)
}

// SetField sets the value of a field with the given name. It returns an error if
// the field is not defined in the schema, or if the type mismatched the field
// type.
func (m *UserConfigMutation) SetField(name string, value ent.Value) error {
	switch name {
	case userconfig.FieldRank:
		v, ok := value.(uint8)
		if !ok {
			return fmt.Errorf("unexpected type %T for field %s", value, name)
		}
		m.SetRank(v)
		return nil
	case userconfig.FieldWorking:
		v, ok := value.(uint8)
		if !ok {
			return fmt.Errorf("unexpected type %T for field %s", value, name)
		}
		m.SetWorking(v)
		return nil
	case userconfig.FieldBreak:
		v, ok := value.(uint8)
		if !ok {
			return fmt.Errorf("unexpected type %T for field %s", value, name)
		}
		m.SetBreak(v)
		return nil
	}
	return fmt.Errorf("unknown UserConfig field %s", name)
}

// AddedFields returns all numeric fields that were incremented/decremented during
// this mutation.
func (m *UserConfigMutation) AddedFields() []string {
	var fields []string
	if m.addrank != nil {
		fields = append(fields, userconfig.FieldRank)
	}
	if m.addworking != nil {
		fields = append(fields, userconfig.FieldWorking)
	}
	if m.add_break != nil {
		fields = append(fields, userconfig.FieldBreak)
	}
	return fields
}

// AddedField returns the numeric value that was incremented/decremented on a field
// with the given name. The second boolean return value indicates that this field
// was not set, or was not defined in the schema.
func (m *UserConfigMutation) AddedField(name string) (ent.Value, bool) {
	switch name {
	case userconfig.FieldRank:
		return m.AddedRank()
	case userconfig.FieldWorking:
		return m.AddedWorking()
	case userconfig.FieldBreak:
		return m.AddedBreak()
	}
	return nil, false
}

// AddField adds the value to the field with the given name. It returns an error if
// the field is not defined in the schema, or if the type mismatched the field
// type.
func (m *UserConfigMutation) AddField(name string, value ent.Value) error {
	switch name {
	case userconfig.FieldRank:
		v, ok := value.(uint8)
		if !ok {
			return fmt.Errorf("unexpected type %T for field %s", value, name)
		}
		m.AddRank(v)
		return nil
	case userconfig.FieldWorking:
		v, ok := value.(uint8)
		if !ok {
			return fmt.Errorf("unexpected type %T for field %s", value, name)
		}
		m.AddWorking(v)
		return nil
	case userconfig.FieldBreak:
		v, ok := value.(uint8)
		if !ok {
			return fmt.Errorf("unexpected type %T for field %s", value, name)
		}
		m.AddBreak(v)
		return nil
	}
	return fmt.Errorf("unknown UserConfig numeric field %s", name)
}

// ClearedFields returns all nullable fields that were cleared during this
// mutation.
func (m *UserConfigMutation) ClearedFields() []string {
	return nil
}

// FieldCleared returns a boolean indicating if a field with the given name was
// cleared in this mutation.
func (m *UserConfigMutation) FieldCleared(name string) bool {
	_, ok := m.clearedFields[name]
	return ok
}

// ClearField clears the value of the field with the given name. It returns an
// error if the field is not defined in the schema.
func (m *UserConfigMutation) ClearField(name string) error {
	return fmt.Errorf("unknown UserConfig nullable field %s", name)
}

// ResetField resets all changes in the mutation for the field with the given name.
// It returns an error if the field is not defined in the schema.
func (m *UserConfigMutation) ResetField(name string) error {
	switch name {
	case userconfig.FieldRank:
		m.ResetRank()
		return nil
	case userconfig.FieldWorking:
		m.ResetWorking()
		return nil
	case userconfig.FieldBreak:
		m.ResetBreak()
		return nil
	}
	return fmt.Errorf("unknown UserConfig field %s", name)
}

// AddedEdges returns all edge names that were set/added in this mutation.
func (m *UserConfigMutation) AddedEdges() []string {
	edges := make([]string, 0, 1)
	if m.users != nil {
		edges = append(edges, userconfig.EdgeUsers)
	}
	return edges
}

// AddedIDs returns all IDs (to other nodes) that were added for the given edge
// name in this mutation.
func (m *UserConfigMutation) AddedIDs(name string) []ent.Value {
	switch name {
	case userconfig.EdgeUsers:
		if id := m.users; id != nil {
			return []ent.Value{*id}
		}
	}
	return nil
}

// RemovedEdges returns all edge names that were removed in this mutation.
func (m *UserConfigMutation) RemovedEdges() []string {
	edges := make([]string, 0, 1)
	return edges
}

// RemovedIDs returns all IDs (to other nodes) that were removed for the edge with
// the given name in this mutation.
func (m *UserConfigMutation) RemovedIDs(name string) []ent.Value {
	switch name {
	}
	return nil
}

// ClearedEdges returns all edge names that were cleared in this mutation.
func (m *UserConfigMutation) ClearedEdges() []string {
	edges := make([]string, 0, 1)
	if m.clearedusers {
		edges = append(edges, userconfig.EdgeUsers)
	}
	return edges
}

// EdgeCleared returns a boolean which indicates if the edge with the given name
// was cleared in this mutation.
func (m *UserConfigMutation) EdgeCleared(name string) bool {
	switch name {
	case userconfig.EdgeUsers:
		return m.clearedusers
	}
	return false
}

// ClearEdge clears the value of the edge with the given name. It returns an error
// if that edge is not defined in the schema.
func (m *UserConfigMutation) ClearEdge(name string) error {
	switch name {
	case userconfig.EdgeUsers:
		m.ClearUsers()
		return nil
	}
	return fmt.Errorf("unknown UserConfig unique edge %s", name)
}

// ResetEdge resets all changes to the edge with the given name in this mutation.
// It returns an error if the edge is not defined in the schema.
func (m *UserConfigMutation) ResetEdge(name string) error {
	switch name {
	case userconfig.EdgeUsers:
		m.ResetUsers()
		return nil
	}
	return fmt.Errorf("unknown UserConfig edge %s", name)
}

// UserTomatoMutation represents an operation that mutates the UserTomato nodes in the graph.
type UserTomatoMutation struct {
	config
	op            Op
	typ           string
	id            *int
	created_at    *time.Time
	updated_at    *time.Time
	start_time    *time.Time
	color         *usertomato.Color
	remain_time   *time.Time
	end_time      *time.Time
	clearedFields map[string]struct{}
	users         *int
	clearedusers  bool
	done          bool
	oldValue      func(context.Context) (*UserTomato, error)
	predicates    []predicate.UserTomato
}

var _ ent.Mutation = (*UserTomatoMutation)(nil)

// usertomatoOption allows management of the mutation configuration using functional options.
type usertomatoOption func(*UserTomatoMutation)

// newUserTomatoMutation creates new mutation for the UserTomato entity.
func newUserTomatoMutation(c config, op Op, opts ...usertomatoOption) *UserTomatoMutation {
	m := &UserTomatoMutation{
		config:        c,
		op:            op,
		typ:           TypeUserTomato,
		clearedFields: make(map[string]struct{}),
	}
	for _, opt := range opts {
		opt(m)
	}
	return m
}

// withUserTomatoID sets the ID field of the mutation.
func withUserTomatoID(id int) usertomatoOption {
	return func(m *UserTomatoMutation) {
		var (
			err   error
			once  sync.Once
			value *UserTomato
		)
		m.oldValue = func(ctx context.Context) (*UserTomato, error) {
			once.Do(func() {
				if m.done {
					err = fmt.Errorf("querying old values post mutation is not allowed")
				} else {
					value, err = m.Client().UserTomato.Get(ctx, id)
				}
			})
			return value, err
		}
		m.id = &id
	}
}

// withUserTomato sets the old UserTomato of the mutation.
func withUserTomato(node *UserTomato) usertomatoOption {
	return func(m *UserTomatoMutation) {
		m.oldValue = func(context.Context) (*UserTomato, error) {
			return node, nil
		}
		m.id = &node.ID
	}
}

// Client returns a new `ent.Client` from the mutation. If the mutation was
// executed in a transaction (ent.Tx), a transactional client is returned.
func (m UserTomatoMutation) Client() *Client {
	client := &Client{config: m.config}
	client.init()
	return client
}

// Tx returns an `ent.Tx` for mutations that were executed in transactions;
// it returns an error otherwise.
func (m UserTomatoMutation) Tx() (*Tx, error) {
	if _, ok := m.driver.(*txDriver); !ok {
		return nil, fmt.Errorf("ent: mutation is not running in a transaction")
	}
	tx := &Tx{config: m.config}
	tx.init()
	return tx, nil
}

// ID returns the ID value in the mutation. Note that the ID is only available
// if it was provided to the builder or after it was returned from the database.
func (m *UserTomatoMutation) ID() (id int, exists bool) {
	if m.id == nil {
		return
	}
	return *m.id, true
}

// SetCreatedAt sets the "created_at" field.
func (m *UserTomatoMutation) SetCreatedAt(t time.Time) {
	m.created_at = &t
}

// CreatedAt returns the value of the "created_at" field in the mutation.
func (m *UserTomatoMutation) CreatedAt() (r time.Time, exists bool) {
	v := m.created_at
	if v == nil {
		return
	}
	return *v, true
}

// OldCreatedAt returns the old "created_at" field's value of the UserTomato entity.
// If the UserTomato object wasn't provided to the builder, the object is fetched from the database.
// An error is returned if the mutation operation is not UpdateOne, or the database query fails.
func (m *UserTomatoMutation) OldCreatedAt(ctx context.Context) (v time.Time, err error) {
	if !m.op.Is(OpUpdateOne) {
		return v, fmt.Errorf("OldCreatedAt is only allowed on UpdateOne operations")
	}
	if m.id == nil || m.oldValue == nil {
		return v, fmt.Errorf("OldCreatedAt requires an ID field in the mutation")
	}
	oldValue, err := m.oldValue(ctx)
	if err != nil {
		return v, fmt.Errorf("querying old value for OldCreatedAt: %w", err)
	}
	return oldValue.CreatedAt, nil
}

// ResetCreatedAt resets all changes to the "created_at" field.
func (m *UserTomatoMutation) ResetCreatedAt() {
	m.created_at = nil
}

// SetUpdatedAt sets the "updated_at" field.
func (m *UserTomatoMutation) SetUpdatedAt(t time.Time) {
	m.updated_at = &t
}

// UpdatedAt returns the value of the "updated_at" field in the mutation.
func (m *UserTomatoMutation) UpdatedAt() (r time.Time, exists bool) {
	v := m.updated_at
	if v == nil {
		return
	}
	return *v, true
}

// OldUpdatedAt returns the old "updated_at" field's value of the UserTomato entity.
// If the UserTomato object wasn't provided to the builder, the object is fetched from the database.
// An error is returned if the mutation operation is not UpdateOne, or the database query fails.
func (m *UserTomatoMutation) OldUpdatedAt(ctx context.Context) (v time.Time, err error) {
	if !m.op.Is(OpUpdateOne) {
		return v, fmt.Errorf("OldUpdatedAt is only allowed on UpdateOne operations")
	}
	if m.id == nil || m.oldValue == nil {
		return v, fmt.Errorf("OldUpdatedAt requires an ID field in the mutation")
	}
	oldValue, err := m.oldValue(ctx)
	if err != nil {
		return v, fmt.Errorf("querying old value for OldUpdatedAt: %w", err)
	}
	return oldValue.UpdatedAt, nil
}

// ResetUpdatedAt resets all changes to the "updated_at" field.
func (m *UserTomatoMutation) ResetUpdatedAt() {
	m.updated_at = nil
}

// SetUserID sets the "user_id" field.
func (m *UserTomatoMutation) SetUserID(i int) {
	m.users = &i
}

// UserID returns the value of the "user_id" field in the mutation.
func (m *UserTomatoMutation) UserID() (r int, exists bool) {
	v := m.users
	if v == nil {
		return
	}
	return *v, true
}

// OldUserID returns the old "user_id" field's value of the UserTomato entity.
// If the UserTomato object wasn't provided to the builder, the object is fetched from the database.
// An error is returned if the mutation operation is not UpdateOne, or the database query fails.
func (m *UserTomatoMutation) OldUserID(ctx context.Context) (v int, err error) {
	if !m.op.Is(OpUpdateOne) {
		return v, fmt.Errorf("OldUserID is only allowed on UpdateOne operations")
	}
	if m.id == nil || m.oldValue == nil {
		return v, fmt.Errorf("OldUserID requires an ID field in the mutation")
	}
	oldValue, err := m.oldValue(ctx)
	if err != nil {
		return v, fmt.Errorf("querying old value for OldUserID: %w", err)
	}
	return oldValue.UserID, nil
}

// ResetUserID resets all changes to the "user_id" field.
func (m *UserTomatoMutation) ResetUserID() {
	m.users = nil
}

// SetStartTime sets the "start_time" field.
func (m *UserTomatoMutation) SetStartTime(t time.Time) {
	m.start_time = &t
}

// StartTime returns the value of the "start_time" field in the mutation.
func (m *UserTomatoMutation) StartTime() (r time.Time, exists bool) {
	v := m.start_time
	if v == nil {
		return
	}
	return *v, true
}

// OldStartTime returns the old "start_time" field's value of the UserTomato entity.
// If the UserTomato object wasn't provided to the builder, the object is fetched from the database.
// An error is returned if the mutation operation is not UpdateOne, or the database query fails.
func (m *UserTomatoMutation) OldStartTime(ctx context.Context) (v time.Time, err error) {
	if !m.op.Is(OpUpdateOne) {
		return v, fmt.Errorf("OldStartTime is only allowed on UpdateOne operations")
	}
	if m.id == nil || m.oldValue == nil {
		return v, fmt.Errorf("OldStartTime requires an ID field in the mutation")
	}
	oldValue, err := m.oldValue(ctx)
	if err != nil {
		return v, fmt.Errorf("querying old value for OldStartTime: %w", err)
	}
	return oldValue.StartTime, nil
}

// ResetStartTime resets all changes to the "start_time" field.
func (m *UserTomatoMutation) ResetStartTime() {
	m.start_time = nil
}

// SetColor sets the "color" field.
func (m *UserTomatoMutation) SetColor(u usertomato.Color) {
	m.color = &u
}

// Color returns the value of the "color" field in the mutation.
func (m *UserTomatoMutation) Color() (r usertomato.Color, exists bool) {
	v := m.color
	if v == nil {
		return
	}
	return *v, true
}

// OldColor returns the old "color" field's value of the UserTomato entity.
// If the UserTomato object wasn't provided to the builder, the object is fetched from the database.
// An error is returned if the mutation operation is not UpdateOne, or the database query fails.
func (m *UserTomatoMutation) OldColor(ctx context.Context) (v usertomato.Color, err error) {
	if !m.op.Is(OpUpdateOne) {
		return v, fmt.Errorf("OldColor is only allowed on UpdateOne operations")
	}
	if m.id == nil || m.oldValue == nil {
		return v, fmt.Errorf("OldColor requires an ID field in the mutation")
	}
	oldValue, err := m.oldValue(ctx)
	if err != nil {
		return v, fmt.Errorf("querying old value for OldColor: %w", err)
	}
	return oldValue.Color, nil
}

// ResetColor resets all changes to the "color" field.
func (m *UserTomatoMutation) ResetColor() {
	m.color = nil
}

// SetRemainTime sets the "remain_time" field.
func (m *UserTomatoMutation) SetRemainTime(t time.Time) {
	m.remain_time = &t
}

// RemainTime returns the value of the "remain_time" field in the mutation.
func (m *UserTomatoMutation) RemainTime() (r time.Time, exists bool) {
	v := m.remain_time
	if v == nil {
		return
	}
	return *v, true
}

// OldRemainTime returns the old "remain_time" field's value of the UserTomato entity.
// If the UserTomato object wasn't provided to the builder, the object is fetched from the database.
// An error is returned if the mutation operation is not UpdateOne, or the database query fails.
func (m *UserTomatoMutation) OldRemainTime(ctx context.Context) (v time.Time, err error) {
	if !m.op.Is(OpUpdateOne) {
		return v, fmt.Errorf("OldRemainTime is only allowed on UpdateOne operations")
	}
	if m.id == nil || m.oldValue == nil {
		return v, fmt.Errorf("OldRemainTime requires an ID field in the mutation")
	}
	oldValue, err := m.oldValue(ctx)
	if err != nil {
		return v, fmt.Errorf("querying old value for OldRemainTime: %w", err)
	}
	return oldValue.RemainTime, nil
}

// ResetRemainTime resets all changes to the "remain_time" field.
func (m *UserTomatoMutation) ResetRemainTime() {
	m.remain_time = nil
}

// SetEndTime sets the "end_time" field.
func (m *UserTomatoMutation) SetEndTime(t time.Time) {
	m.end_time = &t
}

// EndTime returns the value of the "end_time" field in the mutation.
func (m *UserTomatoMutation) EndTime() (r time.Time, exists bool) {
	v := m.end_time
	if v == nil {
		return
	}
	return *v, true
}

// OldEndTime returns the old "end_time" field's value of the UserTomato entity.
// If the UserTomato object wasn't provided to the builder, the object is fetched from the database.
// An error is returned if the mutation operation is not UpdateOne, or the database query fails.
func (m *UserTomatoMutation) OldEndTime(ctx context.Context) (v *time.Time, err error) {
	if !m.op.Is(OpUpdateOne) {
		return v, fmt.Errorf("OldEndTime is only allowed on UpdateOne operations")
	}
	if m.id == nil || m.oldValue == nil {
		return v, fmt.Errorf("OldEndTime requires an ID field in the mutation")
	}
	oldValue, err := m.oldValue(ctx)
	if err != nil {
		return v, fmt.Errorf("querying old value for OldEndTime: %w", err)
	}
	return oldValue.EndTime, nil
}

// ClearEndTime clears the value of the "end_time" field.
func (m *UserTomatoMutation) ClearEndTime() {
	m.end_time = nil
	m.clearedFields[usertomato.FieldEndTime] = struct{}{}
}

// EndTimeCleared returns if the "end_time" field was cleared in this mutation.
func (m *UserTomatoMutation) EndTimeCleared() bool {
	_, ok := m.clearedFields[usertomato.FieldEndTime]
	return ok
}

// ResetEndTime resets all changes to the "end_time" field.
func (m *UserTomatoMutation) ResetEndTime() {
	m.end_time = nil
	delete(m.clearedFields, usertomato.FieldEndTime)
}

// SetUsersID sets the "users" edge to the User entity by id.
func (m *UserTomatoMutation) SetUsersID(id int) {
	m.users = &id
}

// ClearUsers clears the "users" edge to the User entity.
func (m *UserTomatoMutation) ClearUsers() {
	m.clearedusers = true
}

// UsersCleared reports if the "users" edge to the User entity was cleared.
func (m *UserTomatoMutation) UsersCleared() bool {
	return m.clearedusers
}

// UsersID returns the "users" edge ID in the mutation.
func (m *UserTomatoMutation) UsersID() (id int, exists bool) {
	if m.users != nil {
		return *m.users, true
	}
	return
}

// UsersIDs returns the "users" edge IDs in the mutation.
// Note that IDs always returns len(IDs) <= 1 for unique edges, and you should use
// UsersID instead. It exists only for internal usage by the builders.
func (m *UserTomatoMutation) UsersIDs() (ids []int) {
	if id := m.users; id != nil {
		ids = append(ids, *id)
	}
	return
}

// ResetUsers resets all changes to the "users" edge.
func (m *UserTomatoMutation) ResetUsers() {
	m.users = nil
	m.clearedusers = false
}

// Where appends a list predicates to the UserTomatoMutation builder.
func (m *UserTomatoMutation) Where(ps ...predicate.UserTomato) {
	m.predicates = append(m.predicates, ps...)
}

// Op returns the operation name.
func (m *UserTomatoMutation) Op() Op {
	return m.op
}

// Type returns the node type of this mutation (UserTomato).
func (m *UserTomatoMutation) Type() string {
	return m.typ
}

// Fields returns all fields that were changed during this mutation. Note that in
// order to get all numeric fields that were incremented/decremented, call
// AddedFields().
func (m *UserTomatoMutation) Fields() []string {
	fields := make([]string, 0, 7)
	if m.created_at != nil {
		fields = append(fields, usertomato.FieldCreatedAt)
	}
	if m.updated_at != nil {
		fields = append(fields, usertomato.FieldUpdatedAt)
	}
	if m.users != nil {
		fields = append(fields, usertomato.FieldUserID)
	}
	if m.start_time != nil {
		fields = append(fields, usertomato.FieldStartTime)
	}
	if m.color != nil {
		fields = append(fields, usertomato.FieldColor)
	}
	if m.remain_time != nil {
		fields = append(fields, usertomato.FieldRemainTime)
	}
	if m.end_time != nil {
		fields = append(fields, usertomato.FieldEndTime)
	}
	return fields
}

// Field returns the value of a field with the given name. The second boolean
// return value indicates that this field was not set, or was not defined in the
// schema.
func (m *UserTomatoMutation) Field(name string) (ent.Value, bool) {
	switch name {
	case usertomato.FieldCreatedAt:
		return m.CreatedAt()
	case usertomato.FieldUpdatedAt:
		return m.UpdatedAt()
	case usertomato.FieldUserID:
		return m.UserID()
	case usertomato.FieldStartTime:
		return m.StartTime()
	case usertomato.FieldColor:
		return m.Color()
	case usertomato.FieldRemainTime:
		return m.RemainTime()
	case usertomato.FieldEndTime:
		return m.EndTime()
	}
	return nil, false
}

// OldField returns the old value of the field from the database. An error is
// returned if the mutation operation is not UpdateOne, or the query to the
// database failed.
func (m *UserTomatoMutation) OldField(ctx context.Context, name string) (ent.Value, error) {
	switch name {
	case usertomato.FieldCreatedAt:
		return m.OldCreatedAt(ctx)
	case usertomato.FieldUpdatedAt:
		return m.OldUpdatedAt(ctx)
	case usertomato.FieldUserID:
		return m.OldUserID(ctx)
	case usertomato.FieldStartTime:
		return m.OldStartTime(ctx)
	case usertomato.FieldColor:
		return m.OldColor(ctx)
	case usertomato.FieldRemainTime:
		return m.OldRemainTime(ctx)
	case usertomato.FieldEndTime:
		return m.OldEndTime(ctx)
	}
	return nil, fmt.Errorf("unknown UserTomato field %s", name)
}

// SetField sets the value of a field with the given name. It returns an error if
// the field is not defined in the schema, or if the type mismatched the field
// type.
func (m *UserTomatoMutation) SetField(name string, value ent.Value) error {
	switch name {
	case usertomato.FieldCreatedAt:
		v, ok := value.(time.Time)
		if !ok {
			return fmt.Errorf("unexpected type %T for field %s", value, name)
		}
		m.SetCreatedAt(v)
		return nil
	case usertomato.FieldUpdatedAt:
		v, ok := value.(time.Time)
		if !ok {
			return fmt.Errorf("unexpected type %T for field %s", value, name)
		}
		m.SetUpdatedAt(v)
		return nil
	case usertomato.FieldUserID:
		v, ok := value.(int)
		if !ok {
			return fmt.Errorf("unexpected type %T for field %s", value, name)
		}
		m.SetUserID(v)
		return nil
	case usertomato.FieldStartTime:
		v, ok := value.(time.Time)
		if !ok {
			return fmt.Errorf("unexpected type %T for field %s", value, name)
		}
		m.SetStartTime(v)
		return nil
	case usertomato.FieldColor:
		v, ok := value.(usertomato.Color)
		if !ok {
			return fmt.Errorf("unexpected type %T for field %s", value, name)
		}
		m.SetColor(v)
		return nil
	case usertomato.FieldRemainTime:
		v, ok := value.(time.Time)
		if !ok {
			return fmt.Errorf("unexpected type %T for field %s", value, name)
		}
		m.SetRemainTime(v)
		return nil
	case usertomato.FieldEndTime:
		v, ok := value.(time.Time)
		if !ok {
			return fmt.Errorf("unexpected type %T for field %s", value, name)
		}
		m.SetEndTime(v)
		return nil
	}
	return fmt.Errorf("unknown UserTomato field %s", name)
}

// AddedFields returns all numeric fields that were incremented/decremented during
// this mutation.
func (m *UserTomatoMutation) AddedFields() []string {
	var fields []string
	return fields
}

// AddedField returns the numeric value that was incremented/decremented on a field
// with the given name. The second boolean return value indicates that this field
// was not set, or was not defined in the schema.
func (m *UserTomatoMutation) AddedField(name string) (ent.Value, bool) {
	switch name {
	}
	return nil, false
}

// AddField adds the value to the field with the given name. It returns an error if
// the field is not defined in the schema, or if the type mismatched the field
// type.
func (m *UserTomatoMutation) AddField(name string, value ent.Value) error {
	switch name {
	}
	return fmt.Errorf("unknown UserTomato numeric field %s", name)
}

// ClearedFields returns all nullable fields that were cleared during this
// mutation.
func (m *UserTomatoMutation) ClearedFields() []string {
	var fields []string
	if m.FieldCleared(usertomato.FieldEndTime) {
		fields = append(fields, usertomato.FieldEndTime)
	}
	return fields
}

// FieldCleared returns a boolean indicating if a field with the given name was
// cleared in this mutation.
func (m *UserTomatoMutation) FieldCleared(name string) bool {
	_, ok := m.clearedFields[name]
	return ok
}

// ClearField clears the value of the field with the given name. It returns an
// error if the field is not defined in the schema.
func (m *UserTomatoMutation) ClearField(name string) error {
	switch name {
	case usertomato.FieldEndTime:
		m.ClearEndTime()
		return nil
	}
	return fmt.Errorf("unknown UserTomato nullable field %s", name)
}

// ResetField resets all changes in the mutation for the field with the given name.
// It returns an error if the field is not defined in the schema.
func (m *UserTomatoMutation) ResetField(name string) error {
	switch name {
	case usertomato.FieldCreatedAt:
		m.ResetCreatedAt()
		return nil
	case usertomato.FieldUpdatedAt:
		m.ResetUpdatedAt()
		return nil
	case usertomato.FieldUserID:
		m.ResetUserID()
		return nil
	case usertomato.FieldStartTime:
		m.ResetStartTime()
		return nil
	case usertomato.FieldColor:
		m.ResetColor()
		return nil
	case usertomato.FieldRemainTime:
		m.ResetRemainTime()
		return nil
	case usertomato.FieldEndTime:
		m.ResetEndTime()
		return nil
	}
	return fmt.Errorf("unknown UserTomato field %s", name)
}

// AddedEdges returns all edge names that were set/added in this mutation.
func (m *UserTomatoMutation) AddedEdges() []string {
	edges := make([]string, 0, 1)
	if m.users != nil {
		edges = append(edges, usertomato.EdgeUsers)
	}
	return edges
}

// AddedIDs returns all IDs (to other nodes) that were added for the given edge
// name in this mutation.
func (m *UserTomatoMutation) AddedIDs(name string) []ent.Value {
	switch name {
	case usertomato.EdgeUsers:
		if id := m.users; id != nil {
			return []ent.Value{*id}
		}
	}
	return nil
}

// RemovedEdges returns all edge names that were removed in this mutation.
func (m *UserTomatoMutation) RemovedEdges() []string {
	edges := make([]string, 0, 1)
	return edges
}

// RemovedIDs returns all IDs (to other nodes) that were removed for the edge with
// the given name in this mutation.
func (m *UserTomatoMutation) RemovedIDs(name string) []ent.Value {
	switch name {
	}
	return nil
}

// ClearedEdges returns all edge names that were cleared in this mutation.
func (m *UserTomatoMutation) ClearedEdges() []string {
	edges := make([]string, 0, 1)
	if m.clearedusers {
		edges = append(edges, usertomato.EdgeUsers)
	}
	return edges
}

// EdgeCleared returns a boolean which indicates if the edge with the given name
// was cleared in this mutation.
func (m *UserTomatoMutation) EdgeCleared(name string) bool {
	switch name {
	case usertomato.EdgeUsers:
		return m.clearedusers
	}
	return false
}

// ClearEdge clears the value of the edge with the given name. It returns an error
// if that edge is not defined in the schema.
func (m *UserTomatoMutation) ClearEdge(name string) error {
	switch name {
	case usertomato.EdgeUsers:
		m.ClearUsers()
		return nil
	}
	return fmt.Errorf("unknown UserTomato unique edge %s", name)
}

// ResetEdge resets all changes to the edge with the given name in this mutation.
// It returns an error if the edge is not defined in the schema.
func (m *UserTomatoMutation) ResetEdge(name string) error {
	switch name {
	case usertomato.EdgeUsers:
		m.ResetUsers()
		return nil
	}
	return fmt.Errorf("unknown UserTomato edge %s", name)
}
