// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"fmt"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/go-gosh/tomato/app/ent/predicate"
	"github.com/go-gosh/tomato/app/ent/user"
	"github.com/go-gosh/tomato/app/ent/userconfig"
)

// UserConfigUpdate is the builder for updating UserConfig entities.
type UserConfigUpdate struct {
	config
	hooks    []Hook
	mutation *UserConfigMutation
}

// Where appends a list predicates to the UserConfigUpdate builder.
func (ucu *UserConfigUpdate) Where(ps ...predicate.UserConfig) *UserConfigUpdate {
	ucu.mutation.Where(ps...)
	return ucu
}

// SetUserID sets the "user_id" field.
func (ucu *UserConfigUpdate) SetUserID(i int) *UserConfigUpdate {
	ucu.mutation.SetUserID(i)
	return ucu
}

// SetRank sets the "rank" field.
func (ucu *UserConfigUpdate) SetRank(u uint8) *UserConfigUpdate {
	ucu.mutation.ResetRank()
	ucu.mutation.SetRank(u)
	return ucu
}

// AddRank adds u to the "rank" field.
func (ucu *UserConfigUpdate) AddRank(u int8) *UserConfigUpdate {
	ucu.mutation.AddRank(u)
	return ucu
}

// SetWorking sets the "working" field.
func (ucu *UserConfigUpdate) SetWorking(u uint) *UserConfigUpdate {
	ucu.mutation.ResetWorking()
	ucu.mutation.SetWorking(u)
	return ucu
}

// AddWorking adds u to the "working" field.
func (ucu *UserConfigUpdate) AddWorking(u int) *UserConfigUpdate {
	ucu.mutation.AddWorking(u)
	return ucu
}

// SetBreak sets the "break" field.
func (ucu *UserConfigUpdate) SetBreak(u uint) *UserConfigUpdate {
	ucu.mutation.ResetBreak()
	ucu.mutation.SetBreak(u)
	return ucu
}

// AddBreak adds u to the "break" field.
func (ucu *UserConfigUpdate) AddBreak(u int) *UserConfigUpdate {
	ucu.mutation.AddBreak(u)
	return ucu
}

// SetUsersID sets the "users" edge to the User entity by ID.
func (ucu *UserConfigUpdate) SetUsersID(id int) *UserConfigUpdate {
	ucu.mutation.SetUsersID(id)
	return ucu
}

// SetUsers sets the "users" edge to the User entity.
func (ucu *UserConfigUpdate) SetUsers(u *User) *UserConfigUpdate {
	return ucu.SetUsersID(u.ID)
}

// Mutation returns the UserConfigMutation object of the builder.
func (ucu *UserConfigUpdate) Mutation() *UserConfigMutation {
	return ucu.mutation
}

// ClearUsers clears the "users" edge to the User entity.
func (ucu *UserConfigUpdate) ClearUsers() *UserConfigUpdate {
	ucu.mutation.ClearUsers()
	return ucu
}

// Save executes the query and returns the number of nodes affected by the update operation.
func (ucu *UserConfigUpdate) Save(ctx context.Context) (int, error) {
	var (
		err      error
		affected int
	)
	if len(ucu.hooks) == 0 {
		if err = ucu.check(); err != nil {
			return 0, err
		}
		affected, err = ucu.sqlSave(ctx)
	} else {
		var mut Mutator = MutateFunc(func(ctx context.Context, m Mutation) (Value, error) {
			mutation, ok := m.(*UserConfigMutation)
			if !ok {
				return nil, fmt.Errorf("unexpected mutation type %T", m)
			}
			if err = ucu.check(); err != nil {
				return 0, err
			}
			ucu.mutation = mutation
			affected, err = ucu.sqlSave(ctx)
			mutation.done = true
			return affected, err
		})
		for i := len(ucu.hooks) - 1; i >= 0; i-- {
			if ucu.hooks[i] == nil {
				return 0, fmt.Errorf("ent: uninitialized hook (forgotten import ent/runtime?)")
			}
			mut = ucu.hooks[i](mut)
		}
		if _, err := mut.Mutate(ctx, ucu.mutation); err != nil {
			return 0, err
		}
	}
	return affected, err
}

// SaveX is like Save, but panics if an error occurs.
func (ucu *UserConfigUpdate) SaveX(ctx context.Context) int {
	affected, err := ucu.Save(ctx)
	if err != nil {
		panic(err)
	}
	return affected
}

// Exec executes the query.
func (ucu *UserConfigUpdate) Exec(ctx context.Context) error {
	_, err := ucu.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (ucu *UserConfigUpdate) ExecX(ctx context.Context) {
	if err := ucu.Exec(ctx); err != nil {
		panic(err)
	}
}

// check runs all checks and user-defined validators on the builder.
func (ucu *UserConfigUpdate) check() error {
	if _, ok := ucu.mutation.UsersID(); ucu.mutation.UsersCleared() && !ok {
		return errors.New(`ent: clearing a required unique edge "UserConfig.users"`)
	}
	return nil
}

func (ucu *UserConfigUpdate) sqlSave(ctx context.Context) (n int, err error) {
	_spec := &sqlgraph.UpdateSpec{
		Node: &sqlgraph.NodeSpec{
			Table:   userconfig.Table,
			Columns: userconfig.Columns,
			ID: &sqlgraph.FieldSpec{
				Type:   field.TypeInt,
				Column: userconfig.FieldID,
			},
		},
	}
	if ps := ucu.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := ucu.mutation.Rank(); ok {
		_spec.Fields.Set = append(_spec.Fields.Set, &sqlgraph.FieldSpec{
			Type:   field.TypeUint8,
			Value:  value,
			Column: userconfig.FieldRank,
		})
	}
	if value, ok := ucu.mutation.AddedRank(); ok {
		_spec.Fields.Add = append(_spec.Fields.Add, &sqlgraph.FieldSpec{
			Type:   field.TypeUint8,
			Value:  value,
			Column: userconfig.FieldRank,
		})
	}
	if value, ok := ucu.mutation.Working(); ok {
		_spec.Fields.Set = append(_spec.Fields.Set, &sqlgraph.FieldSpec{
			Type:   field.TypeUint,
			Value:  value,
			Column: userconfig.FieldWorking,
		})
	}
	if value, ok := ucu.mutation.AddedWorking(); ok {
		_spec.Fields.Add = append(_spec.Fields.Add, &sqlgraph.FieldSpec{
			Type:   field.TypeUint,
			Value:  value,
			Column: userconfig.FieldWorking,
		})
	}
	if value, ok := ucu.mutation.Break(); ok {
		_spec.Fields.Set = append(_spec.Fields.Set, &sqlgraph.FieldSpec{
			Type:   field.TypeUint,
			Value:  value,
			Column: userconfig.FieldBreak,
		})
	}
	if value, ok := ucu.mutation.AddedBreak(); ok {
		_spec.Fields.Add = append(_spec.Fields.Add, &sqlgraph.FieldSpec{
			Type:   field.TypeUint,
			Value:  value,
			Column: userconfig.FieldBreak,
		})
	}
	if ucu.mutation.UsersCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   userconfig.UsersTable,
			Columns: []string{userconfig.UsersColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: &sqlgraph.FieldSpec{
					Type:   field.TypeInt,
					Column: user.FieldID,
				},
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := ucu.mutation.UsersIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   userconfig.UsersTable,
			Columns: []string{userconfig.UsersColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: &sqlgraph.FieldSpec{
					Type:   field.TypeInt,
					Column: user.FieldID,
				},
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	if n, err = sqlgraph.UpdateNodes(ctx, ucu.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{userconfig.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return 0, err
	}
	return n, nil
}

// UserConfigUpdateOne is the builder for updating a single UserConfig entity.
type UserConfigUpdateOne struct {
	config
	fields   []string
	hooks    []Hook
	mutation *UserConfigMutation
}

// SetUserID sets the "user_id" field.
func (ucuo *UserConfigUpdateOne) SetUserID(i int) *UserConfigUpdateOne {
	ucuo.mutation.SetUserID(i)
	return ucuo
}

// SetRank sets the "rank" field.
func (ucuo *UserConfigUpdateOne) SetRank(u uint8) *UserConfigUpdateOne {
	ucuo.mutation.ResetRank()
	ucuo.mutation.SetRank(u)
	return ucuo
}

// AddRank adds u to the "rank" field.
func (ucuo *UserConfigUpdateOne) AddRank(u int8) *UserConfigUpdateOne {
	ucuo.mutation.AddRank(u)
	return ucuo
}

// SetWorking sets the "working" field.
func (ucuo *UserConfigUpdateOne) SetWorking(u uint) *UserConfigUpdateOne {
	ucuo.mutation.ResetWorking()
	ucuo.mutation.SetWorking(u)
	return ucuo
}

// AddWorking adds u to the "working" field.
func (ucuo *UserConfigUpdateOne) AddWorking(u int) *UserConfigUpdateOne {
	ucuo.mutation.AddWorking(u)
	return ucuo
}

// SetBreak sets the "break" field.
func (ucuo *UserConfigUpdateOne) SetBreak(u uint) *UserConfigUpdateOne {
	ucuo.mutation.ResetBreak()
	ucuo.mutation.SetBreak(u)
	return ucuo
}

// AddBreak adds u to the "break" field.
func (ucuo *UserConfigUpdateOne) AddBreak(u int) *UserConfigUpdateOne {
	ucuo.mutation.AddBreak(u)
	return ucuo
}

// SetUsersID sets the "users" edge to the User entity by ID.
func (ucuo *UserConfigUpdateOne) SetUsersID(id int) *UserConfigUpdateOne {
	ucuo.mutation.SetUsersID(id)
	return ucuo
}

// SetUsers sets the "users" edge to the User entity.
func (ucuo *UserConfigUpdateOne) SetUsers(u *User) *UserConfigUpdateOne {
	return ucuo.SetUsersID(u.ID)
}

// Mutation returns the UserConfigMutation object of the builder.
func (ucuo *UserConfigUpdateOne) Mutation() *UserConfigMutation {
	return ucuo.mutation
}

// ClearUsers clears the "users" edge to the User entity.
func (ucuo *UserConfigUpdateOne) ClearUsers() *UserConfigUpdateOne {
	ucuo.mutation.ClearUsers()
	return ucuo
}

// Select allows selecting one or more fields (columns) of the returned entity.
// The default is selecting all fields defined in the entity schema.
func (ucuo *UserConfigUpdateOne) Select(field string, fields ...string) *UserConfigUpdateOne {
	ucuo.fields = append([]string{field}, fields...)
	return ucuo
}

// Save executes the query and returns the updated UserConfig entity.
func (ucuo *UserConfigUpdateOne) Save(ctx context.Context) (*UserConfig, error) {
	var (
		err  error
		node *UserConfig
	)
	if len(ucuo.hooks) == 0 {
		if err = ucuo.check(); err != nil {
			return nil, err
		}
		node, err = ucuo.sqlSave(ctx)
	} else {
		var mut Mutator = MutateFunc(func(ctx context.Context, m Mutation) (Value, error) {
			mutation, ok := m.(*UserConfigMutation)
			if !ok {
				return nil, fmt.Errorf("unexpected mutation type %T", m)
			}
			if err = ucuo.check(); err != nil {
				return nil, err
			}
			ucuo.mutation = mutation
			node, err = ucuo.sqlSave(ctx)
			mutation.done = true
			return node, err
		})
		for i := len(ucuo.hooks) - 1; i >= 0; i-- {
			if ucuo.hooks[i] == nil {
				return nil, fmt.Errorf("ent: uninitialized hook (forgotten import ent/runtime?)")
			}
			mut = ucuo.hooks[i](mut)
		}
		v, err := mut.Mutate(ctx, ucuo.mutation)
		if err != nil {
			return nil, err
		}
		nv, ok := v.(*UserConfig)
		if !ok {
			return nil, fmt.Errorf("unexpected node type %T returned from UserConfigMutation", v)
		}
		node = nv
	}
	return node, err
}

// SaveX is like Save, but panics if an error occurs.
func (ucuo *UserConfigUpdateOne) SaveX(ctx context.Context) *UserConfig {
	node, err := ucuo.Save(ctx)
	if err != nil {
		panic(err)
	}
	return node
}

// Exec executes the query on the entity.
func (ucuo *UserConfigUpdateOne) Exec(ctx context.Context) error {
	_, err := ucuo.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (ucuo *UserConfigUpdateOne) ExecX(ctx context.Context) {
	if err := ucuo.Exec(ctx); err != nil {
		panic(err)
	}
}

// check runs all checks and user-defined validators on the builder.
func (ucuo *UserConfigUpdateOne) check() error {
	if _, ok := ucuo.mutation.UsersID(); ucuo.mutation.UsersCleared() && !ok {
		return errors.New(`ent: clearing a required unique edge "UserConfig.users"`)
	}
	return nil
}

func (ucuo *UserConfigUpdateOne) sqlSave(ctx context.Context) (_node *UserConfig, err error) {
	_spec := &sqlgraph.UpdateSpec{
		Node: &sqlgraph.NodeSpec{
			Table:   userconfig.Table,
			Columns: userconfig.Columns,
			ID: &sqlgraph.FieldSpec{
				Type:   field.TypeInt,
				Column: userconfig.FieldID,
			},
		},
	}
	id, ok := ucuo.mutation.ID()
	if !ok {
		return nil, &ValidationError{Name: "id", err: errors.New(`ent: missing "UserConfig.id" for update`)}
	}
	_spec.Node.ID.Value = id
	if fields := ucuo.fields; len(fields) > 0 {
		_spec.Node.Columns = make([]string, 0, len(fields))
		_spec.Node.Columns = append(_spec.Node.Columns, userconfig.FieldID)
		for _, f := range fields {
			if !userconfig.ValidColumn(f) {
				return nil, &ValidationError{Name: f, err: fmt.Errorf("ent: invalid field %q for query", f)}
			}
			if f != userconfig.FieldID {
				_spec.Node.Columns = append(_spec.Node.Columns, f)
			}
		}
	}
	if ps := ucuo.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := ucuo.mutation.Rank(); ok {
		_spec.Fields.Set = append(_spec.Fields.Set, &sqlgraph.FieldSpec{
			Type:   field.TypeUint8,
			Value:  value,
			Column: userconfig.FieldRank,
		})
	}
	if value, ok := ucuo.mutation.AddedRank(); ok {
		_spec.Fields.Add = append(_spec.Fields.Add, &sqlgraph.FieldSpec{
			Type:   field.TypeUint8,
			Value:  value,
			Column: userconfig.FieldRank,
		})
	}
	if value, ok := ucuo.mutation.Working(); ok {
		_spec.Fields.Set = append(_spec.Fields.Set, &sqlgraph.FieldSpec{
			Type:   field.TypeUint,
			Value:  value,
			Column: userconfig.FieldWorking,
		})
	}
	if value, ok := ucuo.mutation.AddedWorking(); ok {
		_spec.Fields.Add = append(_spec.Fields.Add, &sqlgraph.FieldSpec{
			Type:   field.TypeUint,
			Value:  value,
			Column: userconfig.FieldWorking,
		})
	}
	if value, ok := ucuo.mutation.Break(); ok {
		_spec.Fields.Set = append(_spec.Fields.Set, &sqlgraph.FieldSpec{
			Type:   field.TypeUint,
			Value:  value,
			Column: userconfig.FieldBreak,
		})
	}
	if value, ok := ucuo.mutation.AddedBreak(); ok {
		_spec.Fields.Add = append(_spec.Fields.Add, &sqlgraph.FieldSpec{
			Type:   field.TypeUint,
			Value:  value,
			Column: userconfig.FieldBreak,
		})
	}
	if ucuo.mutation.UsersCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   userconfig.UsersTable,
			Columns: []string{userconfig.UsersColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: &sqlgraph.FieldSpec{
					Type:   field.TypeInt,
					Column: user.FieldID,
				},
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := ucuo.mutation.UsersIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   userconfig.UsersTable,
			Columns: []string{userconfig.UsersColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: &sqlgraph.FieldSpec{
					Type:   field.TypeInt,
					Column: user.FieldID,
				},
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	_node = &UserConfig{config: ucuo.config}
	_spec.Assign = _node.assignValues
	_spec.ScanValues = _node.scanValues
	if err = sqlgraph.UpdateNode(ctx, ucuo.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{userconfig.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	return _node, nil
}
